version: "3.7"
   
services:
  web:
    build: .
    container_name: jungle-devs-challenger-web-prd
    command: gunicorn --bind=:8000 --reload main.wsgi
    volumes:
      - ./app:/app
    expose: 
      - 8000
    env_file:
      - ./.env.web.prd
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jungle-devs-challenger

  db:
    image: postgres:13
    container_name: jungle-devs-challenger-db-prd
    volumes:
      - ./data/db-prd:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 18
    env_file:
    - ./.env.db.prd
    networks:
      - jungle-devs-challenger

  nginx:
    build: ./nginx
    container_name: jungle-devs-challenger-nginx-prd
    volumes:
      - ./app/media:/usr/src/app/media
      - ./app/static:/usr/src/app/static
    ports:
      - "9100:80"
    depends_on:
      - web
    networks:
      - jungle-devs-challenger
      
networks:
  jungle-devs-challenger:
    name: jungle-devs-challenger-prd
    driver: bridge